version: "3.8"

services:

  hestiacp:
    image: "jhmaverick/hestiacp:${HESTIACP_TAG:-latest}"
    container_name: "hestiacp-server"
    restart: "unless-stopped"
    hostname: "$HESTIACP_HOSTNAME"
    privileged: true
    depends_on:
      - mariadb
    environment:
      SAFE_MODE: "${SAFE_MODE:-}"
      CONTAINER_INFRA: "$CONTAINER_INFRA"
      MAIL_ADMIN: "${MAIL_ADMIN:-}"
    labels:
      - "Hestia Control Panel"
    ports:
      - "80:80"
      - "443:443"
      - "8083:8083"
      # Proxy TCP to MariaDB
      - "3306:3306"
      # DNS
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:953:953/tcp"
      # FTP
      - "20:20"
      - "21:21"
      - "12000-12100:12000-12100"
      # Container SSH
      - "22222:22222"
      # SMTP and SMTP over TLS
      - "25:25"
      - "465:465"
      - "587:587"
      - "2525:2525"
      # IMAP and IMAP over SSL
      - "143:143"
      - "993:993"
      # POP3 and POP3 over SSL
      - "110:110"
      - "995:995"
    volumes:
      - /data/backup:/backup
      - /data/conf:/conf
      - /data/home:/home
      - mariadb-logs:/var/log/mysql
    networks:
      - default

  mariadb:
    image: mariadb:10.6
    container_name: "hestiacp-mariadb"
    restart: "unless-stopped"
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_ROOT_HOST: "%"
      MARIADB_INITDB_SKIP_TZINFO: 1
    volumes:
      - /data/mariadb:/var/lib/mysql
      - mariadb-logs:/var/log/mysql
    command: [ "mysqld", "--innodb-flush-method=fsync", "--max-connections=1000", "--max-user-connections=150" ]
    networks:
      - default

volumes:
  mariadb-logs:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
